# Generated by Django 6.0.1 on 2026-02-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0003_alter_address_city_alter_address_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
