# Generated by Django 6.0.1 on 2026-02-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0004_category_estimated_price_category_estimated_time'),
        ('manage_user', '0005_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='manage_service.category'),
        ),
    ]
