# Generated by Django 6.0.1 on 2026-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0006_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
