# Generated by Django 6.0.1 on 2026-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0002_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category_images/default.jpg', null=True, upload_to='category_images/'),
        ),
    ]
