# Generated by Django 6.0.1 on 2026-02-23 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='estimated_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
    ]
