# Generated by Django 6.0.1 on 2026-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0004_category_estimated_price_category_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
