# Generated by Django 6.0.1 on 2026-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0005_servicerequest_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, default='service_images/default.jpg', null=True, upload_to='service_images/'),
        ),
    ]
