# Generated by Django 6.0.1 on 2026-03-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0006_service_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
    ]
