# Generated by Django 6.0.1 on 2026-03-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0007_servicerequest_feedback_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
