# Generated by Django 6.0.1 on 2026-03-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_service', '0008_servicerequest_payment_done'),
        ('manage_user', '0007_profile_average_rating_profile_total_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='manage_user.profile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to='manage_user.profile')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='manage_service.servicerequest')),
            ],
        ),
    ]
